PREFIXES = ["/", "!"]
SUBS = ["subs", "подписки"]
TOP_AI = ["top_ai", "topai"]
POS_AI = ["pos_ai", "posai"]
TOP_ML = ["top_ml", "topml"]
POS_ML = ["pos_ml", "posml"]
SUB_AI_FORUM = ["sub_ai_forum"]
UNSUB_AI_FORUM = ["unsub_ai_forum"]
TOP = ["top"]
POS = ["pos"]
CONFIG = ["config"]

ADMIN = ["admin"]
HELP = ["start", "help", "помощь", "хелб", "памаги"]
