PREFIXES = ["/", "!"]
SUBS = ["subs", "подписки"]

TOP_AI = ["top_ai", "topai"]
TOOP_AI = ["toop_ai", "toopai"]
POS_AI = ["pos_ai", "posai"]
POOS_AI = ["poos_ai", "poosai"]
SUB_AI_FORUM = ["sub_ai_forum"]
UNSUB_AI_FORUM = ["unsub_ai_forum"]
SUB_AI_GAMES = ["sub_ai_games"]
UNSUB_AI_GAMES = ["unsub_ai_games"]

TOP_ML = ["top_ml", "topml"]
TOOP_ML = ["toop_ml", "toopml"]
POS_ML = ["pos_ml", "posml"]
POOS_ML = ["poos_ml", "poosml"]

TOP = ["top", "топ"]
TOOP = ["toop", "тооп"]
POS = ["pos"]
POOS = ["poos"]

CONFIG = ["config"]
ADMIN = ["admin"]
HELP = ["start", "help", "помощь", "хелб", "памаги"]
